import type { NextPage } from 'next';
import Head from 'next/head';
import AppView from '@/components/App/AppView';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AllZone HRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppView />
    </div>
  );
};

export default Home;
